### ISSUE TITLE
IE compatibility: Date is shown as NaN and user image strikes through timeline

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-statushistory-presentation#8]

**Comment by innerjoin** [comment]
The problem is that jazz returns dates in a non-conforming format. According to [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601), the following formats are valid:
- 2017-10-16T02:17:15+00:00
- 2017-10-16T02:17:15Z
Jazz however uses the following format:
2017-10-16T02:17:15+0000
which is missing the colon (:). Most browsers tolerate this format, but IE is very strict and therefore does not accept this date.

**Comment by innerjoin** [comment]
Resolved by [Release 2.2.2](https://github.com/jazz-community/rtc-statushistory-presentation/releases/tag/v2.2.2)
